export const homeData = [
  {
    id: 1,
    name: "Star Dust",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home1.jpg",
    video: "https://www.youtube.com/watch?v=-wwv427DAvA",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "skull island",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/home2.jpg",
    video: "https://www.youtube.com/watch?v=Oml-RZX0xi4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Real Jackpot",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "https://www.youtube.com/watch?v=jKHjcy7niwo",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Shadow",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home4.jpg",
    video: "https://www.youtube.com/watch?v=OIE-I-Ug9Oo",
    date: "12-Aug-2015",
  },
];
export const upcome = [
  {
    id: 1,
    cover: "../images/u1.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=NenlQz-FkLY",
  },
  {
    id: 2,
    cover: "../images/u2.jpg",
    name: "Stree",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=maESU3fQl2Q",
  },
  {
    id: 3,
    cover: "../images/u3.jpg",
    name: "EK Paheli",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=rGsXo6cjKyE",
  },
  {
    id: 4,
    cover: "../images/u4.jpg",
    name: "URI: The Surgical Strike",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=ga1PMLM0Op4",
  },
  {
    id: 5,
    cover: "../images/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=rGsXo6cjKyE",
  },
];
export const latest = [
  {
    id: 1,
    cover: "../images/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=YaVzNjkl1YM",
  },
  {
    id: 2,
    cover: "../images/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=LoTOtGdY0b8",
  },
  {
    id: 3,
    cover: "../images/u1.jpg",
    name: "Secret Agent",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=rNIFgHrqIto",
  },
  {
    id: 4,
    cover: "../images/u5.jpg",
    name: "The Rajabheem",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=nA8VZFCn6n8",
  },
  {
    id: 5,
    cover: "../images/u4.jpg",
    name: "Paltan",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=A2x9BEISWHs",
  },
];

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/slide3.jpg",
    date: "20-FEB-2010",
  },
];
export const recommended = [
  {
    id: 4,
    cover: "../images/rec1.jpg",
    name: "Soccer Fighters",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=KnsU4rAKiEg",
  },
  {
    id: 5,
    cover: "../images/rec2.jpg",
    name: "Charlie",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=mIaKS3OtqEg",
  },
  {
    id: 1,
    cover: "../images/rec3.jpg",
    name: "The NUN",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=VSaEdshUCzA",
  },
  {
    id: 2,
    cover: "../images/rec4.jpg",
    name: "Kaw Kaw Kaw",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=ha_r0dAMGco",
  },
  {
    id: 3,
    cover: "../images/u3.jpg",
    name: "PARI",
    time: "2hr : 38mins",
    videoUrl: "https://www.youtube.com/watch?v=Kf7SxLAPZ3c",
  },
];
